version: "3.8"

services:
  backend:
    build: .
    container_name: refind-backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - MONGO_URI=mongodb://mongo:27017/refind_db
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo:6
    container_name: refind-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
